services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - coolify
    volumes:
      - /srv/ap-queren-hapuque/dist:/usr/share/nginx/html:ro
      - /srv/ap-queren-hapuque/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "caddy=app.querenhapuque.com"
      - "caddy.encode=gzip"
      - "caddy.reverse_proxy={{upstreams 80}}"
      - "caddy.try_files={path} /index.html"
networks:
  coolify:
    external: true